#!/usr/bin/env bash

set -eo pipefail

# XXX figure out a better way to specify these.
NODE_VERSION='6.11.1'
NPM_VERSION='4.2.0'

get_ubuntu_release() {
    lsb_release --codename --short
}

install_node() {
    if [[ $(get_ubuntu_release) == "precise" ]]; then
        source "$HOME/nvm/nvm.sh"
    else
        source "/opt/circleci/.nvm/nvm.sh"
    fi
    printf 'Logging: About to install node'
    # On trusty/Ubuntu 14, nvm is available in the environment
    nvm install "v$NODE_VERSION"
    nvm alias default "v$NODE_VERSION"
    nvm use "v$NODE_VERSION"
}

main() {
    install_node

    node --version
    npm --version

    yarn

    # if npm --loglevel verbose install > npm-install.log 2>&1 ; then
    #     printf '\033[95mAll dependencies installed!\033[0m'
    # else
    #     tail -n2000 npm-install.log
    #     exit 1
    # fi
}
main
